# Generated by Django 4.2.15 on 2024-08-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='analytics',
            field=models.OneToOneField(db_column='author_analytics_id', on_delete=django.db.models.deletion.CASCADE, to='authors.authoranalytics'),
        ),
    ]
